<?php

namespace Database\Seeders;

use App\Models\PartnershipProgram;
use Illuminate\Database\Seeder;

class PartnershipProgramSeeder extends Seeder
{
    public function run(): void
    {
        $programs = [
            [
                'slug'              => 'franchise',
                'name'              => 'Franchise',
                'icon'              => 'award-fill',
                'color_hex'         => '#d4a017',
                'image_url'         => 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&h=400&fit=crop',
                'badge_label'       => 'Franchise',
                'panel_title'       => 'Program Franchise AROMAS',
                'panel_subtitle'    => 'Kelola gerai resmi AROMAS dengan merek, sistem, dan dukungan operasional penuh dari kami.',
                'info_items'        => [
                    ['icon'=>'cash-coin','label'=>'Investasi Awal','value'=>'Rp 50 Jt – 150 Jt','note'=>'Bergantung ukuran gerai','color_class'=>'clr-gold'],
                    ['icon'=>'graph-up-arrow','label'=>'Estimasi ROI','value'=>'12 – 18 Bulan','note'=>'Rata-rata mitra aktif','color_class'=>'clr-green'],
                    ['icon'=>'geo-alt-fill','label'=>'Wilayah Tersedia','value'=>'34 Provinsi','note'=>'Area eksklusif per zona','color_class'=>'clr-gold'],
                    ['icon'=>'box-seam-fill','label'=>'Min. Order Bulanan','value'=>'500 Liter','note'=>'Semua varian produk','color_class'=>'clr-green'],
                    ['icon'=>'calendar-range','label'=>'Durasi Kontrak','value'=>'3 – 5 Tahun','note'=>'Dapat diperpanjang','color_class'=>'clr-gold'],
                    ['icon'=>'percent','label'=>'Royalti','value'=>'3% – 5%','note'=>'Dari omzet bulanan','color_class'=>'clr-green'],
                ],
                'benefits'          => [
                    ['text'=>'Hak eksklusif menggunakan merek AROMAS di wilayah Anda'],
                    ['text'=>'Sistem operasional & SOP terstandarisasi siap pakai'],
                    ['text'=>'Pelatihan intensif staf & manajemen bisnis'],
                    ['text'=>'Materi pemasaran & desain gerai lengkap'],
                    ['text'=>'Dukungan iklan nasional dari AROMAS'],
                    ['text'=>'Harga khusus mitra franchise'],
                    ['text'=>'Business coach & pendampingan berkala'],
                ],
                'requirements'      => [
                    ['text'=>'WNI usia min. 21 tahun / Badan usaha legal'],
                    ['text'=>'Modal investasi sesuai paket yang dipilih'],
                    ['text'=>'Memiliki lokasi strategis (min. 20 m²)'],
                    ['text'=>'Komitmen penuh menjalankan SOP AROMAS'],
                    ['text'=>'Rekening bank aktif atas nama pemohon'],
                    ['text'=>'Tidak memiliki merek kompetitor di lokasi sama'],
                ],
                'steps'             => [
                    ['label'=>'Pengajuan Online','sub'=>'Isi formulir pendaftaran'],
                    ['label'=>'Verifikasi & Survey','sub'=>'Tim kami menghubungi Anda'],
                    ['label'=>'Presentasi & Negosiasi','sub'=>'Diskusi proposal bisnis'],
                    ['label'=>'Tanda Tangan MoU','sub'=>'Penandatanganan kontrak'],
                    ['label'=>'Pelatihan & Setup','sub'=>'Persiapan operasional'],
                    ['label'=>'Grand Opening','sub'=>'Mulai beroperasi!'],
                ],
                'cta_title'         => 'Tertarik Membuka Franchise AROMAS?',
                'cta_subtitle'      => 'Konsultasikan kebutuhan Anda dengan tim kemitraan kami secara gratis.',
                'cta_wa_text'       => 'Halo, saya tertarik program Franchise AROMAS',
                'cta_btn_wa_label'  => 'Konsultasi Gratis',
                'cta_btn_form_label'=> 'Daftar Sekarang',
                'sort_order'        => 1,
                'is_active'         => true,
            ],
            [
                'slug'              => 'distributor',
                'name'              => 'Distributor',
                'icon'              => 'truck-front-fill',
                'color_hex'         => '#228b22',
                'image_url'         => 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200&h=400&fit=crop',
                'badge_label'       => 'Distributor',
                'panel_title'       => 'Program Distributor AROMAS',
                'panel_subtitle'    => 'Kelola distribusi produk AROMAS di wilayah Anda dan raih margin keuntungan kompetitif.',
                'info_items'        => [
                    ['icon'=>'cash-coin','label'=>'Min. Modal Kerja','value'=>'Rp 100 Jt – 500 Jt','note'=>'Disesuaikan kapasitas wilayah','color_class'=>'clr-green'],
                    ['icon'=>'percent','label'=>'Margin Keuntungan','value'=>'8% – 15%','note'=>'Per liter produk','color_class'=>'clr-green'],
                    ['icon'=>'geo-alt-fill','label'=>'Cakupan Wilayah','value'=>'Kab / Kota Eksklusif','note'=>'1 distributor per area','color_class'=>'clr-green'],
                    ['icon'=>'box-seam-fill','label'=>'Min. Order Bulanan','value'=>'5.000 Liter','note'=>'Semua varian produk','color_class'=>'clr-green'],
                    ['icon'=>'building','label'=>'Syarat Gudang','value'=>'Min. 100 m²','note'=>'Milik sendiri / sewa','color_class'=>'clr-green'],
                    ['icon'=>'truck','label'=>'Armada Pengiriman','value'=>'Min. 2 Kendaraan','note'=>'Roda 4 / lebih','color_class'=>'clr-green'],
                ],
                'benefits'          => [
                    ['text'=>'Hak distribusi eksklusif wilayah yang ditetapkan'],
                    ['text'=>'Harga distributor paling kompetitif'],
                    ['text'=>'Dukungan logistik & sistem order online'],
                    ['text'=>'Materi promosi & display produk gratis'],
                    ['text'=>'Target bonus kuartalan & tahunan menarik'],
                    ['text'=>'Prioritas pasokan produk baru'],
                    ['text'=>'Pelatihan tim sales & distribusi'],
                ],
                'requirements'      => [
                    ['text'=>'Badan usaha resmi (PT/CV/UD) terdaftar'],
                    ['text'=>'SIUP & TDP aktif, NPWP perusahaan'],
                    ['text'=>'Memiliki gudang & armada pengiriman'],
                    ['text'=>'Tim sales minimal 3 orang berpengalaman'],
                    ['text'=>'Rekening perusahaan aktif'],
                    ['text'=>'Tidak menjual produk kompetitor langsung'],
                ],
                'steps'             => [
                    ['label'=>'Ajukan Permohonan','sub'=>'Kirim profil perusahaan'],
                    ['label'=>'Review Dokumen','sub'=>'Verifikasi legalitas'],
                    ['label'=>'Site Visit','sub'=>'Tim kami berkunjung'],
                    ['label'=>'Kontrak & PKS','sub'=>'Perjanjian kerjasama'],
                    ['label'=>'Onboarding','sub'=>'Training & orientasi'],
                    ['label'=>'Mulai Distribusi','sub'=>'Operasional aktif'],
                ],
                'cta_title'         => 'Siap Menjadi Distributor AROMAS?',
                'cta_subtitle'      => 'Tim Business Development kami siap mendiskusikan potensi wilayah Anda.',
                'cta_wa_text'       => 'Halo, saya tertarik program Distributor AROMAS',
                'cta_btn_wa_label'  => 'Konsultasi Gratis',
                'cta_btn_form_label'=> 'Ajukan Sekarang',
                'sort_order'        => 2,
                'is_active'         => true,
            ],
            [
                'slug'              => 'agen',
                'name'              => 'Agen / Reseller',
                'icon'              => 'shop-window',
                'color_hex'         => '#0077b6',
                'image_url'         => 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200&h=400&fit=crop',
                'badge_label'       => 'Agen / Reseller',
                'panel_title'       => 'Program Agen & Reseller AROMAS',
                'panel_subtitle'    => 'Program entry-level yang fleksibel untuk individu dan usaha kecil yang ingin menjual produk AROMAS.',
                'info_items'        => [
                    ['icon'=>'cash-coin','label'=>'Modal Awal','value'=>'Rp 5 Jt – 25 Jt','note'=>'Sangat terjangkau','color_class'=>'clr-blue'],
                    ['icon'=>'percent','label'=>'Margin Keuntungan','value'=>'5% – 12%','note'=>'Per produk terjual','color_class'=>'clr-blue'],
                    ['icon'=>'box-seam-fill','label'=>'Min. Order','value'=>'100 Liter / bulan','note'=>'Fleksibel per kebutuhan','color_class'=>'clr-blue'],
                    ['icon'=>'phone-fill','label'=>'Platform Jual','value'=>'Online + Offline','note'=>'Marketplace, sosmed, toko','color_class'=>'clr-blue'],
                    ['icon'=>'calendar-range','label'=>'Durasi','value'=>'1 Tahun','note'=>'Perpanjangan otomatis','color_class'=>'clr-blue'],
                    ['icon'=>'trophy-fill','label'=>'Program Bonus','value'=>'Monthly & Yearly','note'=>'Reward performa terbaik','color_class'=>'clr-blue'],
                ],
                'benefits'          => [
                    ['text'=>'Modal kecil, potensi keuntungan besar'],
                    ['text'=>'Bebas tentukan harga jual di atas HPP'],
                    ['text'=>'Tidak perlu gudang besar, order fleksibel'],
                    ['text'=>'Materi promosi digital siap pakai (caption, banner)'],
                    ['text'=>'Bisa berjualan di marketplace (Tokopedia, Shopee, dll)'],
                    ['text'=>'Komunitas reseller aktif & sharing best practice'],
                    ['text'=>'Upgrade ke level Agen / Distributor tersedia'],
                ],
                'requirements'      => [
                    ['text'=>'WNI usia min. 18 tahun'],
                    ['text'=>'KTP aktif & rekening bank pribadi'],
                    ['text'=>'Memiliki media penjualan (toko / sosmed / marketplace)'],
                    ['text'=>'Komitmen min. order bulanan'],
                    ['text'=>'Mengikuti pelatihan orientasi reseller'],
                ],
                'steps'             => [
                    ['label'=>'Daftar Online','sub'=>'Isi form pendaftaran'],
                    ['label'=>'Verifikasi Data','sub'=>'Proses 1–2 hari kerja'],
                    ['label'=>'Orientasi Online','sub'=>'Pelatihan via Zoom/Meet'],
                    ['label'=>'Aktivasi Akun','sub'=>'Akses portal reseller'],
                    ['label'=>'Order Perdana','sub'=>'Mulai stok produk'],
                    ['label'=>'Mulai Jualan!','sub'=>'Raih keuntungan'],
                ],
                'cta_title'         => 'Mau Jadi Agen atau Reseller AROMAS?',
                'cta_subtitle'      => 'Daftar sekarang, mulai dengan modal kecil dan tumbuh bersama kami.',
                'cta_wa_text'       => 'Halo, saya tertarik program Agen/Reseller AROMAS',
                'cta_btn_wa_label'  => 'Tanya Lebih Lanjut',
                'cta_btn_form_label'=> 'Daftar Gratis',
                'sort_order'        => 3,
                'is_active'         => true,
            ],
            [
                'slug'              => 'maklon',
                'name'              => 'Maklon',
                'icon'              => 'gear-wide-connected',
                'color_hex'         => '#7b2d8b',
                'image_url'         => 'https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=1200&h=400&fit=crop',
                'badge_label'       => 'Maklon',
                'panel_title'       => 'Layanan Maklon / OEM AROMAS',
                'panel_subtitle'    => 'Produksi minyak goreng dengan merek Anda sendiri menggunakan fasilitas & standar kualitas pabrik AROMAS.',
                'info_items'        => [
                    ['icon'=>'layers-fill','label'=>'Min. Order Produksi','value'=>'10.000 Liter','note'=>'Per batch produksi','color_class'=>'clr-purple'],
                    ['icon'=>'box-seam-fill','label'=>'Jenis Kemasan','value'=>'Botol, Jeriken, BIB','note'=>'Sesuai kebutuhan klien','color_class'=>'clr-purple'],
                    ['icon'=>'palette-fill','label'=>'Custom Branding','value'=>'Label & Kemasan','note'=>'Desain sesuai merek Anda','color_class'=>'clr-purple'],
                    ['icon'=>'clock-history','label'=>'Lead Time','value'=>'14 – 30 Hari','note'=>'Per batch produksi','color_class'=>'clr-purple'],
                    ['icon'=>'award-fill','label'=>'Sertifikasi Tersedia','value'=>'Halal, SNI, BPOM','note'=>'Atas nama merek klien','color_class'=>'clr-purple'],
                    ['icon'=>'flask-fill','label'=>'Custom Formula','value'=>'Tersedia','note'=>'Sesuai spesifikasi klien','color_class'=>'clr-purple'],
                ],
                'benefits'          => [
                    ['text'=>'Produksi menggunakan fasilitas pabrik bersertifikat ISO 22000'],
                    ['text'=>'Formulasi khusus sesuai target pasar Anda'],
                    ['text'=>'Desain kemasan & label custom professional'],
                    ['text'=>'Bantuan pengurusan sertifikasi Halal & BPOM'],
                    ['text'=>'Quality control ketat di setiap tahap produksi'],
                    ['text'=>'Laporan COA (Certificate of Analysis) tiap batch'],
                    ['text'=>'Harga produksi kompetitif, skala ekonomis'],
                ],
                'requirements'      => [
                    ['text'=>'Badan usaha resmi (PT/CV) atau perorangan'],
                    ['text'=>'Spesifikasi produk & target pasar yang jelas'],
                    ['text'=>'Desain label / brief branding yang disiapkan'],
                    ['text'=>'Deposit awal 30% dari total nilai produksi'],
                    ['text'=>'NDA (Non-Disclosure Agreement) wajib ditandatangani'],
                    ['text'=>'Komitmen min. order per kerjasama'],
                ],
                'steps'             => [
                    ['label'=>'Brief & Konsultasi','sub'=>'Diskusi kebutuhan produk'],
                    ['label'=>'R&D Formula','sub'=>'Uji coba formulasi'],
                    ['label'=>'Approval Sampel','sub'=>'Persetujuan klien'],
                    ['label'=>'Produksi Massal','sub'=>'Eksekusi di pabrik'],
                    ['label'=>'QC & Pengemasan','sub'=>'Quality control ketat'],
                    ['label'=>'Pengiriman','sub'=>'Produk siap distribusi'],
                ],
                'cta_title'         => 'Tertarik Membangun Merek Minyak Goreng Anda?',
                'cta_subtitle'      => 'Diskusikan spesifikasi dan kebutuhan produksi bersama tim R&D kami.',
                'cta_wa_text'       => 'Halo, saya tertarik layanan Maklon AROMAS',
                'cta_btn_wa_label'  => 'Konsultasi Maklon',
                'cta_btn_form_label'=> 'Kirim Brief',
                'sort_order'        => 4,
                'is_active'         => true,
            ],
            [
                'slug'              => 'implan',
                'name'              => 'Implan Korporasi',
                'icon'              => 'building-fill-up',
                'color_hex'         => '#c0392b',
                'image_url'         => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=400&fit=crop',
                'badge_label'       => 'Implan Korporasi',
                'panel_title'       => 'Program Implan Korporasi AROMAS',
                'panel_subtitle'    => 'Solusi pengadaan minyak goreng terintegrasi khusus untuk perusahaan, instansi, dan korporasi skala besar.',
                'info_items'        => [
                    ['icon'=>'building','label'=>'Target Klien','value'=>'Perusahaan / Instansi','note'=>'BUMN, swasta, pemerintah','color_class'=>'clr-red'],
                    ['icon'=>'layers-fill','label'=>'Min. Order Bulanan','value'=>'50.000 Liter','note'=>'Kontrak jangka panjang','color_class'=>'clr-red'],
                    ['icon'=>'percent','label'=>'Harga Khusus','value'=>'Harga Korporasi','note'=>'Di bawah harga pasaran','color_class'=>'clr-red'],
                    ['icon'=>'truck','label'=>'Pengiriman','value'=>'Door-to-Door','note'=>'Ke lokasi klien langsung','color_class'=>'clr-red'],
                    ['icon'=>'calendar-range','label'=>'Durasi Kontrak','value'=>'1 – 3 Tahun','note'=>'Dapat diperpanjang','color_class'=>'clr-red'],
                    ['icon'=>'headset','label'=>'Account Manager','value'=>'Dedicated 1-on-1','note'=>'Layanan prioritas 24/7','color_class'=>'clr-red'],
                ],
                'benefits'          => [
                    ['text'=>'Harga korporasi eksklusif jauh di bawah harga eceran'],
                    ['text'=>'Pengiriman terjadwal langsung ke lokasi perusahaan'],
                    ['text'=>'Dedicated account manager khusus untuk setiap klien'],
                    ['text'=>'Laporan penggunaan & invoice bulanan terstruktur'],
                    ['text'=>'Kemasan & branding custom atas nama perusahaan klien'],
                    ['text'=>'Jaminan ketersediaan stok & SLA pengiriman tertulis'],
                    ['text'=>'Fleksibilitas pembayaran: NET 30 / NET 60 terms'],
                ],
                'requirements'      => [
                    ['text'=>'Surat permohonan resmi dari perusahaan'],
                    ['text'=>'SIUP, TDP, NPWP perusahaan aktif'],
                    ['text'=>'Estimasi kebutuhan penggunaan per bulan'],
                    ['text'=>'Penandatanganan MoU / PKS korporasi'],
                    ['text'=>'Deposit awal sesuai nilai kontrak'],
                ],
                'steps'             => [
                    ['label'=>'Pengajuan Kebutuhan','sub'=>'Kirim estimasi kebutuhan'],
                    ['label'=>'Survey & Analisa','sub'=>'Tim kami kunjungi lokasi'],
                    ['label'=>'Penawaran Harga','sub'=>'Harga spesial korporasi'],
                    ['label'=>'Kontrak & MoU','sub'=>'Perjanjian kerjasama'],
                    ['label'=>'Setup Pengiriman','sub'=>'Jadwal & rute ditetapkan'],
                    ['label'=>'Mulai Beroperasi','sub'=>'Pasokan rutin aktif'],
                ],
                'cta_title'         => 'Siap Implementasi Solusi Korporasi?',
                'cta_subtitle'      => 'Tim B2B kami siap menyusun proposal khusus sesuai skala perusahaan Anda.',
                'cta_wa_text'       => 'Halo, saya tertarik program Implan Korporasi AROMAS',
                'cta_btn_wa_label'  => 'Konsultasi B2B',
                'cta_btn_form_label'=> 'Ajukan Proposal',
                'sort_order'        => 5,
                'is_active'         => true,
            ],
        ];

        foreach ($programs as $data) {
            PartnershipProgram::firstOrCreate(['slug' => $data['slug']], $data);
        }
    }
}
